---
- name: Swap CapsLock with Escape
  shell: sed -i '/XKBOPTIONS=/c\XKBOPTIONS="caps:swapescape"' /etc/default/keyboard
  become: yes
  # Run the command with priviledged user

- debug:
    msg: "Reboot is required for `Swap CapsLock with Escape` to work"
