- hosts: localhost
  become: true
  roles:
    - { role: keyboard, tags: keyboard }
    - { role: terminal, tags: terminal }
    - { role: font, tags: font }
    - { role: git, tags: git }
    - { role: vscode, tags: vscode }
