---
- name: Install Visual Studio Code
  snap:
    name: code
    classic: yes

# - name: Install VSCode extensions
#   when: no
#   visual_studio_code_extensions:
#     - vscodevim.vim
#     - dendron.dendron
#     - ms-python.python
#     - ms-vscode.cpptools
#     - esbenp.prettier-vscode
#     - vscjava.vscode-java-debug
# # Skipping this as login is more efficient
