---
- name: Install Docker prerequisites
  apt:
    pkg:
    - ca-certificates
    - curl
    - gnupg
    - lsb-release

- name: Add Docker GPG apt Key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg


- name: Get dpkg architecture
  shell: dpkg --print-architecture
  register: deb_architecture
  tags: debug

- name: Add Docker Repository
  apt_repository:
    repo: "deb [arch={{ deb_architecture.stdout }} signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu focal stable"
    state: present

- name: Install Docker
  apt:
    pkg:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-compose-plugin
